@startuml
'https://plantuml.com/state-diagram

state Доска{
    [*] --> Редактирование_доски : Кнопка редактирования нажата
    [*] --> Список_карточек
    state Редактирование_доски{
        [*] --> Ввод_нового_названия
    }
    state Список_карточек{
        state Карточка{
            [*]-->Кнопка_завершения_карточки : Кнопка завершения нажата
            [*]-->Кнопка_удаления_карточки : Кнопка удаления нажата
            [*]-->Редактирование_карточки : Кнопка редактирования нажата
            [*] --> Создание_карточки : Кнопка создания нажата
            state Редактирование_карточки{
                [*] --> Ввод_нового_названия_карточки
                Ввод_нового_названия_карточки --> Ввод_нового_описания
                Ввод_нового_описания --> Выбор_новых_дедлайнов
                Выбор_новых_дедлайнов --> Завершение_редактирования : Кнопка завершения нажата
            }
            state Создание_карточки{
                            [*] --> Ввод_названия_карточки
                            Ввод_названия_карточки --> Ввод_описания
                            Ввод_описания --> Выбор_дедлайнов
                            Выбор_дедлайнов --> Завершение_создания : Кнопка завершения нажата
                        }
        }
    }
    Ввод_нового_названия --> [*]
    Кнопка_завершения_карточки --> [*]
    Кнопка_удаления_карточки --> [*]
    Завершение_редактирования --> [*]
    Завершение_создания --> [*]
}

@enduml