@startuml
'https://plantuml.com/state-diagram

state Страница_Чата{
    [*] --> Кнопка_Добавления_Пользователя_в_чат : Только для чатов компании
    [*] --> Окно_ввода_текста
    [*] --> Кнопка_прикрепления_вложения
    Кнопка_прикрепления_вложения --> Окно_выбора_типа_вложения
    state Окно_выбора_типа_вложения{
        [*] --> Документ
        state Документ{
            [*] --> Выбор_документа_из_локального_хранилища
        }
        [*] --> Фотография
        state Фотография{
            [*] --> Камера
            [*] --> Галлерея
            state Камера{
                [*] --> Создание_снимка
            }
            state Галлерея{
               [*] --> Выбор_фото_из_галлереи
            }
        }

    }
    state Кнопка_Добавления_Пользователя_в_чат{
        [*] --> Список_пользователей_компании
        state Список_пользователей_компании{
            [*] --> Выбор_пользователя
        }
    }
    Окно_ввода_текста --> Кнопка_отправки_сообщения
    Кнопка_отправки_сообщения --> [*]
    Выбор_документа_из_локального_хранилища-->[*]
    Создание_снимка --> [*]
    Выбор_фото_из_галлереи --> [*]
    Выбор_пользователя --> [*]
}

@enduml