@startuml
'https://plantuml.com/state-diagram
state Страница_Чатов{
    state Список_Чатов{
        Нажатие_на_чат --> Страница_Чата
    }
    state Кнопка_создания_чата{
        [*] --> Диалоговое_окно_выбора_чата
        state Диалоговое_окно_выбора_чата{
            [*] --> Диалоговое_окно_создания_личного_чата
            [*] --> Диалоговое_окно_создания_чата_компании
            state Диалоговое_окно_создания_личного_чата{
                [*] -> Выбор_пользователя_компании_из_списка
            }
            state Диалоговое_окно_создания_чата_компании{
                [*] -> Ввод_названия_чата
            }
        }
    }
    Выбор_пользователя_компании_из_списка --> [*]
    Ввод_названия_чата --> [*]

}
state Страница_Чата{
}
@enduml