@startuml
'https://plantuml.com/state-diagram



state Стартовый_экран {
  [*] --> Ввод_логина
  Ввод_логина -> Ввод_пароля
  Ввод_пароля --> Войти
  Войти ---> Страница_профиля : [Логин и пароль верные]
  Войти -> Сообщение_об_ошибке : [Логин и пароль неверные]
  Сообщение_об_ошибке -> Ввод_логина

}

state Страница_профиля{
}

@enduml