@startuml


'https://plantuml.com/state-diagram

state Панель_Навигации{
    Иконка_Профиля --> Страница_Профиля : Нажатие на иконку
    Иконка_Чатов --> Страница_Чатов : Нажатие на иконку
    Иконка_Досок --> Страница_Досок_Компании : Нажатие на иконку
}
state Страница_Профиля{

}
state Страница_Чатов{

}
state Страница_Досок_Компании{

}

@enduml