@startuml
'https://plantuml.com/state-diagram

state Страница_профиля{
    [*]-->Список_Досок
    state Список_Досок{
        [*]-->Доска
        [*]-->Добавление_доски : Кнопка добавления нажата
        [*]-->Выход_из_приложения : Кнопка выхода нажата
        state Добавление_доски{
            [*]->Ввод_названия_доски : Кнопка добавления доски
        }
    }
    Доска --> [*]
    Ввод_названия_доски --> [*]
    Выход_из_приложения --> [*]
}

@enduml