@startuml
'https://plantuml.com/state-diagram

state Страница_досок{
    [*]-->Список_Досок
    state Список_Досок{
        [*]-->Доска
        [*]-->Добавление_доски : Кнопка добавления нажата
        state Добавление_доски{
            [*]->Ввод_названия_доски : Кнопка добавления доски
        }
    }
    Доска --> [*]
    Ввод_названия_доски --> [*]
}

@enduml