@startuml
'https://plantuml.com/class-diagram
    class Constants
    class LoginPage
    class ProfilePage
    class ChatsPage
    class ChatPage
    class TreePage
    class BoardLogic
    class ChatLogic
    class MessageLogic
    class UserLogic
    class Controllers
    class CompanyLogic
    class LocalStorage
    class AppData
    class UserData
    class BoardRequests
    class CardRequests
    class CompanyRequests
    class MessageRequest
    class UserRequests

LoginPage ..> Constants
ProfilePage ..> Constants
ChatsPage ..> Constants
ChatsPage ..> Constants
TreePage ..> Constants
LoginPage ..> Controllers
LoginPage ..> UserLogic
LoginPage ..> Constants
UserLogic ..> UserRequests
ProfilePage ..> BoardRequests
BoardRequests ..> AppData
BoardRequests ..> CardRequests
CardRequests ..> AppData
UserRequests ..> UserData
UserData ..> LocalStorage
ProfilePage ..> AppData
ProfilePage ..> UserData
ProfilePage ..> Constants
ProfilePage ..> BoardLogic
ChatsPage ..> ChatLogic
ChatsPage ..> AppData
ChatsPage ..> Controllers

@enduml