@startuml
'https://plantuml.com/class-diagram

class ChatPage
class MessageLogic
class MessageRequests
class AppData
class UserData
class Controllers
class Constants

ChatPage ..> MessageLogic
ChatPage o- Constants
ChatPage o--- AppData
MessageRequests o-- Constants
MessageLogic o-- MessageRequests
MessageLogic o-- AppData
MessageLogic o-- UserData
MessageLogic o-- Controllers

@enduml