@startuml
'https://plantuml.com/class-diagram

class ChatsPage
class Constants
class Controllers
class MessageLogic
class MessageRequests
class AppData
class UserData
class UserLogic

ChatsPage o- Constants
ChatsPage ..> UserLogic
MessageRequests o--- Constants
MessageLogic o-- Controllers
ChatsPage ..> MessageLogic
MessageLogic o-- MessageRequests
ChatsPage o- AppData
MessageLogic o-- UserData
MessageLogic o-- AppData

@enduml