@startuml
'https://plantuml.com/class-diagram

class LoginPage
class UserLogic
class UserData
class AppData
class Constants
class UserRequests
class LocalStorage
LoginPage o- Constants
LoginPage ..> UserLogic
UserLogic o-- UserData
UserData o-- LocalStorage
UserLogic o-- UserRequests
UserLogic o-- AppData
UserRequests o-- Constants
@enduml