@startuml
'https://plantuml.com/class-diagram

class ProfilePage
class Constants
class CardRequests
class AppData
class UserData
class CardLogic
class Controllers
class UserLogic
class UserRequests

ProfilePage o-- Constants
ProfilePage o-- CardLogic
CardLogic o-- CardRequests
CardLogic o-- AppData
CardLogic o-- Controllers
CardLogic o-- UserLogic
UserLogic o-- UserRequests
UserLogic o-- AppData
ProfilePage o-- UserData
CardRequests o-- Constants
UserRequests o-- Constants

@enduml