@startuml
'https://plantuml.com/class-diagram

class TreePage
class CompanyLogic
class AppData
class BoardLogic
class Controllers
class BoardRequests
class CardRequests
class CardLogic
class CompanyRequests
class Constants

TreePage ..> CompanyLogic
TreePage o-- Constants
CompanyLogic o-- CompanyRequests
CompanyLogic ..> BoardLogic
BoardLogic o-- CardLogic
BoardLogic o-- BoardRequests
BoardLogic o-- Controllers
CardLogic o-- CardRequests
CardLogic o-- Controllers
CompanyLogic o-- AppData
BoardLogic o-- AppData
CompanyRequests o-- Constants
CardRequests o-- Constants
BoardRequests o-- Constants

@enduml