@startuml
'https://plantuml.com/component-diagram


component "Клиент" {
  [Пользовательский интерфейс]
  [Логический слой]
  [Слой хранилища]
  [Запросы]
}

node "Сервер" {
  [Контроллер]
  [API взаимодействия с базой данных]
}

database "База данных" {
  [Обработчик]
  folder "Пользователи" {
    [Идентификатор]
    [Никнейм]
    [Логин]
    [Пароль]
    [Идентификатор компании]
  }
  folder "Токены"{
    [Токен]
    [Идентификатор пользователя]
  }
  folder "Компании" {
     [Идентификатор]
     [Имя]
  }
  folder "Доски" {
     [Идентификатор]
     [Название]
     [Идентификатор компании]
     [Идентификатор пользователя]
  }
  folder "Карточки" {
     [Идентификатор]
     [Название]
     [Описание]
     [Состояние]
     [Идентификатор доски]
     [Дедлайн]
  }
  folder "Чаты"{
     [Идентификатор]
     [Идентификатор чата]
     [Название]
     [Идентификатор пользователя]
     [Приватность]
  }
  folder "История"{
     [Идентификатор]
     [Идентификатор чата]
     [Идентификатор пользователя]
     [Текст]
     [UTC время]
     [Вложения]
  }
}

[Пользовательский интерфейс] - [Логический слой]
[Логический слой] - [Слой хранилища]
[Логический слой] -- [Запросы]
[Запросы] --> [Контроллер]
[Контроллер] -- [API взаимодействия с базой данных]
[API взаимодействия с базой данных] --> [Обработчик]

@enduml