@startuml
'https://plantuml.com/deployment-diagram

actor Пользователь

agent Клиентское_приложение


database База_данных

node Сервер

Пользователь --> Клиентское_приложение
Клиентское_приложение <--> Сервер
Сервер <-> База_данных

@enduml