@startuml
'https://plantuml.com/activity-diagram-beta
|C| Сотрудник отдела
|Л| Руководитель отдела
|Л|
start
    :Нажатие кнопки\nсоздания карточки<
    :Создание новой карточки|
        repeat
            :Ввод названия карточки<
            :Ввод описания карточки<
            :Ввод дедлайнов карточки<
            :Нажатие кнопки 'создать'<
            if(Карточка не повторяется?)is (да) then
                :Добавление новой карточки/
                :Отправка уведомления\nо добавлении новой\nкарточки>
                |C|
                :Получение уведомления\nо добавлении новой\nкарточки<
                stop
            |Л|
            else(нет)
                :Сообщение об ошибке>
            endif
        repeatwhile
@enduml
