@startuml
'https://plantuml.com/activity-diagram-beta
start
    :Нажатие кнопки\nсоздания доски<
    :Создание новой доски|
        repeat
            :Ввод названия доски<
            :Нажатие кнопки 'создать'<
            if(Название уникально?)is (да) then
                :Добавление новой доски/
                stop
            else(нет)
                :Сообщение об ошибке>
@enduml
