@startuml
'https://plantuml.com/activity-diagram-beta
|С| Сотрудник отдела
|Л| Руководитель отдела
|Л|
start
split
    :Нажатие кнопки\nзавершения<
    :Завершение карточки|
    :Изменение состояния карточки/
    :Отправка уведомления\nзавершения карточки>
    |С|
    :Получение уведомления\nзавершения карточки<
    stop
|Л|
splitagain
    :Нажатие кнопки\nудаления<
    :Подтверждение\nудаления<
    :Удаление карточки|
    :Отправка уведомления\nудаления карточки>
    |С|
    :Получение уведомления\nудаления карточки<
    stop
|Л|
splitagain
    :Нажатие кнопки\nредактирования<
    :Редактирование карточки|
    :Ввод названия карточки<
                :Ввод описания карточки<
                :Ввод дедлайнов карточки<
                :Нажатие кнопки 'редактировать'<
    :Изменение данных карточки/
    :Отправка уведомления\nредактирования карточки>
    |С|
    :Получение уведомления\nредактирования карточки<
    stop
endsplit

@enduml
