@startuml
'https://plantuml.com/activity-diagram-beta
|С| Сотрудник отдела
|Л| Руководитель отдела
|Л|
start
    split
    :Нажати кнопки\n'открытия списка\nпользователей'<
    :Нажатие кнопки\n'удаления пользователя\nиз чата'<
    :Удаление сотрудника из чата|
    :Отправка уведомления\nсотруднику\n'об удалении из чата'>
        |С|
        :Получение уведомления\nоб удалении из чата<
        stop
        |Л|
    splitagain
    :Нажатие кнопки\n'добавления пользователя\nв чат'<
    :Выбор пользователя(ей)\nиз списка<
    :Нажатие кнопки подтверждения\nвыбора пользователей<
    :Добавление сотрудника(ов) в чат|
    :Отправка уведомления\nсотруднику(ам)\n'о добавлении в чат>
    |С|
    :Получение уведомления\nо добавлении в чат<
    stop
    |Л|
    splitagain
    :Нажатие кнопки 'удаления чата'<
    :Подтверждение удаления<
    :Удаление чата|
    endsplit
    :Отправка уведомления сотруднику(ам)>
    |С|
    :Получение уведомления\nоб удалении чата<
stop
@enduml
