@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Нажатие кнопки\n'создания новой карточки'<
    :Создание новой карточки|
        repeat
            :Ввод названия карточки<
            :Ввод описания карточки<
            :Ввод дедлайнов карточки<
            :Нажатие кнопки 'создать'<
            if(Карточка не повторяется?)is (да) then
                :Добавление новой карточки/
                stop
            else(нет)
                :Сообщение об ошибке>
            endif
        repeatwhile

@enduml
