@startuml
'https://plantuml.com/activity-diagram-beta
start
split
    :Нажатие кнопки\nзавершения<
    :Завершение карточки|
    :Изменение состояния карточки/
    stop
splitagain
    :Нажатие кнопки\nудаления<
    :Подтверждение\nудаления<
    :Удаление карточки|
    stop
splitagain
    :Нажатие кнопки\nредактирования<
    :Редактирование карточки|
        :Ввод названия карточки<
        :Ввод описания карточки<
        :Ввод дедлайнов карточки<
        :Нажатие кнопки 'редактировать'<
    :Изменение данных карточки/
    stop
endsplit
@enduml
