@startuml
'https://plantuml.com/activity-diagram-beta
|С2| Другие сотрудники в чате
|С1| Сотрудник отправляющий сообщение

start
    :Ввод текста сообщения\nв поле ввода<
    if(Необходимо добавить вложения?) is(да) then
    :Нажатие кнопки\n'добавления вложений'<
    repeat
    :Добавление вложений|
    split
        :Добавление фотографии|
            split
            :Выбор фотографии(ий)\nиз галлереи<
            splitagain
            :Создание снимка<
            endsplit
    splitagain
        :Выбор прикреплямого(ых)\nдокумента(ов)<
    endsplit
    repeatwhile(Не нажата кнопка\n'прикрепить')
    else(нет)
    endif
    :Нажатие кнопки отправки сообщения<
    :Отправка сообщения|
    :Отправка уведомления\nдругим сотрудникам чата>
    |С2|
    :Получение уведомления\nо новом сообщении<

stop

@enduml
