@startuml
'https://plantuml.com/activity-diagram-beta
|К| Компания
|А| Администратор
|К|
start
    |К|
    :Заполнение\nрегистрационного\nбланка]
    :Отпрвака регистрационного бланка>
    |А|
    :Получение регистрационного бланка<
    :Проверка и обработка\nрегистрационных данных]
    if(Ошбики в регистрационных\nданных обнаружены?)is (да) then
    #pink :Отказ в регистрации;
    :Формирование списка\n причин отказа]
    else (нет)
    #lightblue:Одобрение регистрации;
    :Регистрация компании\nи учетных записей\nруководителей отделов]
    endif
    :Формирование ответного письма]
    :Отправка ответного письма>
    |К|
    :Получение овтетного письма<
stop

@enduml
