@startuml
'https://plantuml.com/activity-diagram-beta
|C| Сотрдуник
|Л| Руководитель отдела
|А| Администратор
|Л|
start
    |Л|
    repeat
        :Заполнение\nрегистрационного\nбланка]
        :Отпрвака регистрационного бланка>
        |А|
        :Получение регистрационного бланка<
        :Проверка и обработка\nрегистрационных данных]
        if(Ошбики в регистрационных\nданных обнаружены?)is (да) then
        #pink :Отказ в регистрации;
        :Формирование списка\n причин отказа]
        else (нет)
        #lightblue:Одобрение регистрации;
        :Регистрация учетной\nзаписи сотрудника]
        endif
        :Формирование ответного письма]
        :Отправка ответного письма>
        |Л|
        :Получение овтетного письма<
        if(Регистрация одобрена?)is (да) then
        :Отправка данных\nдля авторизации>
        |C|
            :Получение данных\nдля авторизации<
            stop
        |Л|
        else(нет)
        endif
        repeatwhile
@enduml
